@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Njc5Mzk0ODJ9._wRWIT7rqOscmaiInWqejG1a_TuZsKHTrd49kwNgTyk

### Cities Index Action
GET http://localhost:3000/cities.json

### Cities Show Action
GET http://localhost:3000/cities/5.json

### Cites Create Action
POST http://localhost:3000/cities.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Testgs", 
  "descrption": "Test city", 
  "gas_price": 12.19, 
  "population_percent_change": -100,
  "images": ["strings", "asjdi", "askbdhj"] 
}

### Cities Update Actions
PATCH http://localhost:3000/cities/4.json
Content-Type: application/json

{
  "name": "Testo"
}

### Cities Delete Action
DELETE http://localhost:3000/cities/4.json


### Sessions Create Action

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "kadeillianmt@gmail.com",
  "password": "password"
}

