@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Njg1NDc3MTJ9.6ABZaJ75Z1PZsz2Evn1zt22QkRsHFQxmyPvDnLNcavs

### Cities Index Action
GET https://montana-cost-of-living-api.fly.dev/cities.json

### Cities Show Action
GET https://montana-cost-of-living-api.fly.dev/cities.json

### Cites Create Action
POST https://montana-cost-of-living-api.fly.dev/cities.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Testgs", 
  "descrption": "Test city", 
  "gas_price": 12.19, 
  "population_percent_change": -100,
  "images": ["strings", "asjdi", "askbdhj"] 
}

### Cities Update Actions
PATCH https://montana-cost-of-living-api.fly.dev/cities/4.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Testo"
}

### Cities Delete Action
DELETE https://montana-cost-of-living-api.fly.dev/cities/1.json
Authorization: Bearer {{jwt}}



### Sessions Create Action

POST https://montana-cost-of-living-api.fly.dev/sessions
Content-Type: application/json

{
  "email": "kadeillianmt@gmail.com",
  "password": "password"
}

